[package]
name = "chazi"
version = "0.1.0"
authors = ["patr0nus <dk4rest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chazi_macros = { version = "0.1.0", path = "./chazi_macros" }
wait-timeout = "0.2"
