name: Publish

on:
  workflow_dispatch:
    inputs:
      bumpLevel:
        description: cargo-release bump level
        required: true
        default: 'release'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
    - run: |
        git config --global user.email "dk4rest@gmail.com"
        git config --global user.name "patr0nus"
        cargo install --version=~0.18 cargo-release
        cargo release -v ${INPUT_BUMPLEVEL} --execute --workspace --no-confirm --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
