name: Publish

on:
  workflow_dispatch:
    inputs:
      cr_args:
        description: "cargo-release args (examples: patch --package chazi, --workspace, release --package chazi_macros)"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        wget -O $RUNNER_TEMP/cargo-release.tar.gz https://github.com/crate-ci/cargo-release/releases/download/v0.18.2/cargo-release-v0.18.2-x86_64-unknown-linux-gnu.tar.gz
        tar xf $RUNNER_TEMP/cargo-release.tar.gz -C $RUNNER_TEMP
        git config --global user.email "dk4rest@gmail.com"
        git config --global user.name "patr0nus"
        echo $RUNNER_TEMP/cargo-release release -v ${{ github.event.inputs.cr_args }} --execute --no-confirm
        $RUNNER_TEMP/cargo-release release -v ${{ github.event.inputs.cr_args }} --execute --no-confirm --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
