name: Publish

on:
  workflow_dispatch:
    inputs:
      bumpLevel:
        description: cargo-release bump level
        required: true
        default: 'release'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        wget -O $RUNNER_TEMP/cargo-release.tar.gz https://github.com/crate-ci/cargo-release/releases/download/v0.18.2/cargo-release-v0.18.2-x86_64-unknown-linux-gnu.tar.gz
        tar xf $RUNNER_TEMP/cargo-release.tar.gz -C $RUNNER_TEMP
        git config --global user.email "dk4rest@gmail.com"
        git config --global user.name "patr0nus"
        $RUNNER_TEMP/cargo-release release -v ${INPUT_BUMPLEVEL} --execute --workspace --no-confirm --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
